services:
  webapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: tg-miniapp-produktik247
    restart: unless-stopped
    volumes:
      - ./app:/app
    networks:
      - ngonx-pm_default

networks:
  ngonx-pm_default:
    external: true